/* 🤖 this file was generated by svg-to-ts*/

import { MyIcon } from '../assets/images/svg-compiled/svg/my-icons.model';

export type IconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];

export * from '../assets/images/svg-compiled/svg/app-agh_logo.icon';
export * from '../assets/images/svg-compiled/svg/my-icons.model';
